var data_sv = { 111: { 'ingress' : 'Lätt löpning 15-20 min. <br> Känner du ofta att du skulle vilja komma igång och träna men att du inte har tid? <br> Följande 5 pass är bra för den som vill komma igång med att röra på sig och förbättra sin kondition på ett enkelt, roligt och inte tidskrävande sätt. Passen tar endast runt 15-20 min men ger ändå bra träning. Vill du träna längre, men fortfarande inte för intensivt, kan du kombinera passen med varandra eller med något av bålstyrka och/eller armar och ben programmen. LYCKA TILL! ',
		       'pass1'   : {'rubrik': 'Jogg/gång intervaller',
				    'txt'   : 'Uppvärmning: 5 min gång övergående till lättjogg alternativt lugn gång övergående till gång i raskt takt <br> Tänj 1-3 min (vader, baksida/framsida lår) <br> Spring eller jogga 30 sekunder, gå 2min. Upprepa 3 gånger, gå/jogga lugnt i 3 min som avslutning <br>',
				   }, 
		       'pass2' : {'rubrik' : 'Powerwalk', 
				  'txt'    : 'Spring/jogga intervaller är både ett enkelt och roligt sätt att träna. Med jogga menas i detta pass i princip det långsammaste du kan springa. Med springa menas snababare än jogg, d.v.s. lite mer kraft i steget och jobbigare att utföra. Kom ihåg att det är viktigt att själv hitta en nivå som känns lagom. Det är ingen sprintträning.  <br> Uppvärmning: 5 min powerwalk <br> 3 min tänjningar <br> Spring eller jogga 1 min, gå 2 min. upprepa 3 gånger <br> 2-3 min nedjogg/gå avslappnande',
				 },                 
		       'pass3' : {'rubrik' : 'Backträning', 
				  'txt'    : 'Leta upp en 100-120m lång backe <br> Uppvärmning: Jogga 3-5 min och tänj sedan vad och lårmuskler i 2-3 min (t.ex. benpendlingar och tänjande utfallssteg) <br> Spring upp/gå i rask takt med långa steg för att sedan gå ned för backen <br> Upprepa 3 gånger. <br>  Stretcha eventuellt baklår och vader efteråt. ',
				 },
                 
                       'pass4' : {'rubrik' : 'Powerwalk', 
				  'txt'    : 'Uppvärmning: 5-8 min gång i promenadtempo övergående till powerwalk alternativt 5-8 min powerwalk övergående till lätt jogg <br> 1 km löpning/jogg/powerwalk (välj själv efter humör men håll samma tempo under hela loppet) <br> Jogga eller gå 2-3 min som en avslappnande avslutning <br> ',
				 },		       
		       'pass5' : {'rubrik' : 'Löpskolning', 
				  'txt'    : 'Uppvärmning: 5 min powerwalk/lättjogg <br> Lätt tänjning av <br> framsida/baksida lår (framsida: stå på ett ben, ta tag i ena benet och pressa vadenmot baklåret, knäet ska peka rakt nedåt, upprepa på andra benet) <br> vader (vinkla upp en fot i taget och pressa den mot t.ex. en stolpe, vägg, ett träd eller staket) <br> Löpskolning:  <br> Gå med höga knän på tå först framlänges 30 steg, sedan baklänges 30 steg. Upprepa 3 gånger. <br> Trippla fram med små steg och låga knän i 20m övergående till 20m med höga knän för att sedan övergå till 20m löpning. Tänk på att ha blicken uppåt och att röra armarna rakt framåt hela tiden (helst i 90 graders vinkel)Upprepa 3 gånger. <br> Gå med hälkick (spark i baken) i 20m för att sedan övergå till löpande hälkick i 20m, därefter 20m löpning. Upprepa 3 gånger. <br> Ravellisteg/tennsoldaten (Löp med raka armar och ben på fotbladet) i 20m. Upprepa 3 gånger.<br> 3x100m stegringslopp (gå, jogga, löp, sprinta, löp, jogga, gå) lugn gåvila tillbaka till start. <br> Avsluta med 1-3 min gång/nedjogg för att varva ned. Stretcha vader och lår vid behov. ' ,
				 },
		     },               
                112: { 'ingress' : 'Lätt löpning 35-40 min. <br> Känner du ofta att du skulle vilja komma igång och träna men att du inte har tid? <br> Följande 5 pass är bra för den som vill komma igång med att röra på sig och förbättra sin grundkondition på ett enkelt, roligt sätt. LYCKA TILL! ',
		       'pass1'   : {'rubrik': '100m lopp + hopprep',
				    'txt'   : 'Uppvärmning: 5 min lättjogg <br> Tänj 5 min <br> löpskolning 5-10min <br> 5x100m löpning. Vila genom att gå tillbaka till startpunkten i lugn takt. <br> Hopprep 10 min (100 hopp, 10 korshopp, 10 hopp från sida till sida, 25 hopp höger ben, 25 hopp vänster ben, 100 hopp båda benen. Upprepa 5 gånger.) <br> Nedjogg 5 min <br> Stretcha.',
				   }, 
		       'pass2' : {'rubrik' : 'Backlöpning med gåvila', 
				  'txt'    : 'Uppvärmning: 5 min lätt jogg <br> 5 min tänjningar. <br> 5x backlöpning 120-150m med gågvila 4 min (exempelvis runt motionsspåret mellan backar eller tillbaka till samma backe) <br> Gå ned i egen takt efter behag och sprinta upp för backen. <br> Nedjogg 5-10 min. <br> Stretcha.',
				 },
                       
		       'pass3' : {'rubrik' : 'Fartlek i terräng', 
				  'txt'    : 'Uppvärmning: 5 min lätt jogg <br> 5 min tänjningar. <br> Fartlek i terräng (variera farten efter känsla då du känner dig pigg: ruscha, ta sikte på ett träd och spring dit. <br> Sedan jogga/löp efter behag och ta efter en stund sikte på ett träd eller en backe och spring dit för att gå över till jogg/gång.  <br> Gå/jogga/löp/spring i 30 min. <br> Fartlek är en rolig form av konditionsträning som kommer från Sverige. Även på engelska heter träningen fartlek.  ',
				 },                       
                       'pass4' : {'rubrik' : 'Håll-i-gång-träning', 
				  'txt'    : 'Uppvärmning: 5 min hopprep: 50 vanliga hopp, 10 korshopp, 3 dubbelhopp, 10 hopp baklänges, 10 i sedled, 20 så fort som möjligt. <br> Upprepa 3 gånger. <br> Mät upp en sträcka på 20m och utför sedan följande övningar, 3 gånger av varje. <br> Löp med höga knän 20m, vänd om och sprinta tillbaka, vila 3 min. <br> Hoppa djupa grodhopp 10m och jogga de återstående 10+20m tillbaka. <br> Spring baklänges 20m, sprinta tillbaka. <br> Utfallssteg 20m, jogga tillbaka. <br>  Detta pass ger både kondition och styrka.  ',
				 },		       
		       'pass5' : {'rubrik' : 'Powerwalk + fotstyrka', 
				  'txt'    : '30 min snabb gång/power walk. <br> 5 min fotstyrkeövningar: 50 tåhävningar, gå innåt och utåt med fötterna 20m, tågång 20m, hälgång 20m, gå på insida/utsida av fötterna 20+20m, hoppa från häl till tå 20m, hoppa över linje 20m. <br> Dessa övningar utföres helst barfota på gräs eller sand. ' ,
				  
				 },
		     },    
		113: { 'ingress' : ' Lätt löpning 55-60 min. Vill du träna lite längre men på ett behagligt sätt? Dessa pass är lätta och tar runt en timme att utföra. LYCKA TILL!',
		       'pass1'   : {'rubrik': 'Gissa 200',
				    'txt'   : 'Uppvärmning: 10 min snabb gång + avlsutande 2 min jogg <br> 5 min tänjningar <br> 10 min löpskolning:  <br> Gå med höga knän på tå först framlänges 30 steg, sedan baklänges 30 steg. Upprepa 3 gånger. <br> Trippla fram med små steg och låga knän i 20m övergående till 20m med höga knän för att sedan övergå till 20m löpning. Tänk på att ha blicken uppåt och att röra armarna rakt framåt hela tiden (helst i 90 graders vinkel)Upprepa 3 gånger. <br> Gå med hälkick (spark i baken) i 20m för att sedan övergå till löpande hälkick i 20m, därefter 20m löpning. Upprepa 3 gånger. <br> Ravellisteg/tennsoldaten (Löp med raka armar och ben på fotbladet) i 20m. Upprepa 3 gånger.<br> 100m stegringslopp (gå, jogga, löp, sprinta, löp, jogga, gå) <br> 5x "gissa 200" Bestäm en tid du vill ha på 200m och försök att pricka den, vila 5 min mellan loppen <br> Jogga lugnt och avslappnande i 5 min. <br> Denna träning blir vad du gör den till. Vill du träna hårt kan du välja snabba tider. Om du är en tävlingsmänniska kan du utmana dina vänner på att se vem som prickar sin gissade tid bäst. ' ,
				   },
		       'pass2' : {'rubrik' : 'Barfotalöpning och fotstyrka', 
				  'txt'    : 'Uppvärmning: 10 min snabb gång + avslutande 2 min jogg <br> 5 min tänjningar <br> 10 min löpskolning: <br> Gå med höga knän på tå först framlänges 30 steg, sedan baklänges 30 steg. Upprepa 3 gånger. <br> Trippla fram med små steg och låga knän i 20m övergående till 20m med höga knän för att sedan övergå till 20m löpning. Tänk på att ha blicken uppåt och att röra armarna rakt framåt hela tiden (helst i 90 graders vinkel)Upprepa 3 gånger. <br> Gå med hälkick (spark i baken) i 20m för att sedan övergå till löpande hälkick i 20m, därefter 20m löpning. Upprepa 3 gånger. <br> Ravellisteg/tennsoldaten (Löp med raka armar och ben på fotbladet) i 20m. Upprepa 3 gånger.<br> 100m stegringslopp (gå, jogga, löp, sprinta, löp, jogga, gå) <br> Barfotalöpning på gräs (alternativt löpning på asfalt/grus med barfotaskor): spring 10-20 s, vila 2 min spring 10-20 s upprepa 3 gånger. Vila 5 min och upprepa 3 gånger till. <br>  Fot samt balansövningar 10 min. <br> 5 min nedjogg, 5 min stretch.',
				 },                       
                       'pass3' : {'rubrik' : 'Barfotalöpning och fotstyrka', 
				  'txt'    : 'Uppvärmning: 10 min snabb gång <br> 5 min tänjningar <br> 10 min löpskolning: <br> Gå med höga knän på tå först framlänges 30 steg, sedan baklänges 30 steg. Upprepa 3 gånger. <br> Trippla fram med små steg och låga knän i 20m övergående till 20m med höga knän för att sedan övergå till 20m löpning. Tänk på att ha blicken uppåt och att röra armarna rakt framåt hela tiden (helst i 90 graders vinkel)Upprepa 3 gånger. <br> Gå med hälkick (spark i baken) i 20m för att sedan övergå till löpande hälkick i 20m, därefter 20m löpning. Upprepa 3 gånger. <br> Ravellisteg/tennsoldaten (Löp med raka armar och ben på fotbladet) i 20m. Upprepa 3 gånger.<br> 100m stegringslopp (gå, jogga, löp, sprinta, löp, jogga, gå) <br>Omväxlande gång/jogg i motionsspår med löpstyrkeövningar var 10:e min <br> Aavlutning: gång 5-10 min i valfritt tempo.',
				 },                       
                       'pass4' : {'rubrik' : 'Powerwalk/jogg pass', 
				  'txt'    : 'Gå i lugn takt i 10 min,  <br> öka sedan takten till powerwalk och håll den takten i 10 min, <br> jogga sedan 10 min, för att gå över till powerwalk 10 min,  <br> gå sedan lugnt i 5 min för att sedan jogga 5 min och avslutligen "Powerwalka" 5 min. <br> Avsluta med 5 min lugn gång.',
				 },                       
                       'pass5' : {'rubrik' : 'Powerwalk 55-60 min', 
				  'txt'    : 'Bestäm möte med en trevlig person vid ett motionsspår eller någon annan promenadvänlig plats. <br> Powerwalka tillsammans i 55-60 min. <br> Alternativt gå själv och lyssna på musik eller gå bara och titta på naturen och tänk på vad du vill.',
				 },
		     },
	     	211: { 'ingress' : ' Medel löpning 15-20 min. <br> Känner du ofta att du skulle vilja komma igång och träna men att du inte har tid? <br> Följande 5 pass passar bra för den som känner sig ganska bra tränad och vill träna löpning på ett roligt och inte så tidskrävande sätt. Passen tar endast runt 15-20 min men ger ändå bra träning. Vill du träna längre, men fortfarande inte för intensivt, kan du kombinera passen med varandra eller med något av bålstyrka och/eller armar och ben programmen. LYCKA TILL! ',
		       'pass1'   : {'rubrik': 'Spring/jogga intervaller',
				    'txt'   : 'Uppvärmning: 5 min lätt jogg (lugnt tempo) alternativt 5 min rask gång <br> 3 min tänjningar (t.ex. framsida lår: stå på ett ben, ta tag i ena benet och pressa vaden mot baklåret, knäet ska peka rakt nedåt, upprepa på andra benet <br> Vader: vinkla upp en fot i taget och pressa den mot t.ex. en stolpe, vägg, ett träd eller staket <br> Spring/jogga 30 sekunder, jogga/ gå raskt 1 min . Upprepa 3 gånger vila 3 min genom att gå i lugn takt. <br> Upprepa 2 gånger till med 5 min gåvila mellan andra och tredje serien. <br> Mät upp en 20m lång sträcka för att utföra löpstyrka/gångstyrka övningar. <br> Gå med höga knän i 20m , gå vanligt tillbaka. <br> Gå med höga knän baklänges, gå vanligt tillbaka. Upprepa 3 gånger.  ' ,
				   },
		       'pass2'   : {'rubrik': 'Spring/jogga intervaller',
				    'txt'   : 'Uppvärmning: 3 min lätt jogg (lugnt tempo) alternativt 5 min rask gång <br> 3 min tänjningar (t.ex. framsida lår: stå på ett ben, ta tag i ena benet och pressa vaden mot baklåret, knäet ska peka rakt nedåt, upprepa på andra benet <br> Vader: vinkla upp en fot i taget och pressa den mot t.ex. en stolpe, vägg, ett träd eller staket <br> Spring 2 min jogga 2 min. Upprepa 3 gånger, (Tempo springa: fortare än bekvämt, ej prattempo) <br> Jogga lugnt för att slappna av och få bort eventuell mjölksyra ur benen i 2-3 min. <br> Stretcha vader och lår (inte absolut nödvändigt med stretching efteråt, upp till en själv).   ' ,
				   },                       
                       'pass3'   : {'rubrik': 'Backträning',
				    'txt'   : 'Leta upp en 100-150m lång backe. <br> Uppvärmning: Övergå från lugn jogg till lite fortare jogg på 5 min, i området nära backen. <br> Spring upp gå ned för backen i ett tempo som får pulsen att sjunka något men ändå inte gå ner till normalpuls. Upprepa 5 gånger. <br>  Jogga lugnt efteråt i 5 min och stretcha eventuellt sedan.  ' ,
				   },                   
                       'pass4'   : {'rubrik': 'Kortare tempolöpning',
				    'txt'   : 'Uppvärmning: 5 min lätt jogg (lugnt tempo)  <br> 3 min tänjningar (t.ex. framsida lår: stå på ett ben, ta tag i ena benet och pressa vaden mot baklåret, knäet ska peka rakt nedåt, upprepa på andra benet <br> Vader: vinkla upp en fot i taget och pressa den mot t.ex. en stolpe, vägg, ett träd eller staket <br> 1 km tempolöpning (ansträngande tempo, ej prattempo).  <br> Avslappnande jogg 5 min + eventuellt stretch  ' ,
				   },                       
                       'pass5'   : {'rubrik': 'Fartlek',
				    'txt'   : 'Uppvärmning: 5 min lättjogg. <br> 2 min tänjningar. <br> 2km fartlek: 400m jogg, <br> 100m löp, 50m sprint, 250m jogg, <br> 300m löp, 100m jogg, <br> 100m jogg, 200m löp, 100m jogg, <br> 100m löp, 200m jogg, 100m sprint (jogg: prattempo, löp:högre knälyft, EJ prat, sprint: 90-100% av max) <br> 2 min lugn jogg. <br> Fartlek är en rolig form av konditionsträning som kommer från Sverige. Även på engelska heter träningen fartlek.  ' ,
				   },
		     },
		212: { 'ingress' : 'Medel löpning 35-40 min. <br> Känner du ofta att du skulle vilja komma igång och träna men att du inte har tid? <br> Följande 5 pass är bra för den som vill röra på sig och förbättra sin grundkondition på ett enkelt, roligt sätt. LYCKA TILL!  ',
		       
		       'pass1'   : {'rubrik': '2x5x100m',
				    'txt'   : 'Uppvärmning: 10 min lätt jogg, 5 min tänjningar, 5 min löpskolning, 5x100m, vila jogga tillbaka till startpunkten. <br> Serievila 5 min. <br> 5 min fotövningar, 2 min nedjogg, stretch. ' ,
				   },
		       'pass2' : {'rubrik' : 'Backlöpning med joggvila', 
				  'txt'    : 'Uppvärmning: 5 min lätt jogg, 5 min tänj/stretch, 5x backlöpning 120-150m med omväxlande jogg/gå vila 5 min (exempelvis runt motionsspåret mellan backar eller tillbaka till samma backe), gå/jogga i egen takt efter behag och sprinta upp för backen, nedjogg+stretch',
				 },
		       'pass3' : {'rubrik' : 'Fartlek i terräng', 
				  'txt'    : 'Uppvärmning: 5 min lätt jogg, 3 min tänj/stretch, fartlek i terräng (variera farten efter känsla då pigg: ruscha ta sikte på ett träd och spring dit sedan jogga/löp efter behag, utför detta i a. 20-30 min och jogga sedan lugnti 3-5 min som avslutning. Fartlek är en svensk träningsform som är roligt och inger en känsla av frihet eftersom man går på känsla och bestämmer själv när man vill ta i och hur länge',
				 },
		       'pass4' : {'rubrik' : 'Håll-igång-träning', 
				  'txt'    : 'Uppvärmning: 5 min hopprep: 50 vanliga hopp, 10 korshopp, 3 dubbelhopp, 10 hopp baklänges, 10 i sedled, 20 så fort som möjligt, Wissmanträning',
				 },
		       'pass5' : {'rubrik' : 'Distanslöpning', 
				  'txt'    : '30 min distanslöpning i ganska behaglig fart,  5 min fotövningar: tåhävningar, innåt och utåt med fötterna, tågång, hälgång, insida/utsida, sommarängshopp, hopp över linje (utföres helst barfota på gräs eller sand)',
				 },
		     },
		213: { 'ingress' : 'Medel löpning 55-60 min. <br> Vill du förbättra din kondition genom löpning? Dessa 5 pass är perfekta för det. LYCKA TILL!  ',		       
		       'pass1'   : {'rubrik': '2x5x100m',
				    'txt'   : 'Uppvärmning: 10 min lugn jogg/snabb gång, 5 min tänjningar, 10 min löpskolning, spring 100m gå tillbaka 50m (pulsen ska inte gå ner helt innan man springer igen) tills du kommer i mål (om löpning på bana annars utför 100m lopp backa 50m tills du gjort 7 100mlopp), vila 10 min. Upprepa 1 gång till. <br> 10 min hopprep, fotövningar, nedjogg, stretch ' ,
				   },
		       'pass2' : {'rubrik' : 'Nedåtgående stege', 
				  'txt'    : 'Uppvärmning: 10 min lugn jogg/snabb gång, 5 min tänjningar, 10 min löpskolning, 2x80m stegringslopp (starta gående för att sedan öka), 1x400m, 2x300m, 3x100m vila vila 2 min mellan loppen, tempo: högre än bekvämt, nedjogg 5min, stretch, fotövningar',
				 },
		       'pass3' : {'rubrik' : '5x "gissa 200"', 
				  'txt'    : 'Uppvärmning: 10 min lugn jogg/snabb gång, 5 min tänjningar, 10 min löpskolning, 5x "gissa 200", bestäm en tid du vill ha på 200m och försök att pricka den, vila 5 min mellan loppen, nedjogg, stretch. <br> Denna träning blir vad du gör den till. Vill du träna hårt kan du välja snabba tider. Om du är en tävlingsmänniska kan du utmana dina vänner på att se vem som prickar sin gissade tid bäst. ',
				 },
		       'pass4' : {'rubrik' : 'Barfotalöpning på gräs (alternativt träning i barefootrunningshoes på grus)', 
				  'txt'    : 'Uppvärmning: 10 min lugn jogg/snabb gång, 5 min tänjningar, 10 min löpskolning, barfotalöpning på gräs: spring 20-30 s, vila 1 min spring 20-30 s upprepa 5 gånger vila 5 min och upprepa 5 gånger till, 3x20m mångsteg, 3x10m grodhopp, fot samt balansövningar 10 min, 5 min nedjogg, stretch',
				 },
		       'pass5' : {'rubrik' : 'Fartlek varvat löpstyrkeövningar', 
				  'txt'    : 'Uppvärmning: 10 min lugn jogg/snabb gång, 5 min tänjningar, 10 min löpskolning, omväxlande jogg/löp i motionsspår med löpstyrkeövningar var 7:e min, nedjogg 5-10 min',
				 },
		       
		     },
		311: { 'ingress' : 'Svår löpning 15-20 min. <br> INGRESS ',
		       'pass1'   : {'rubrik': ' Springa30/jogga30 intervaller',
				    'txt'   : 'Uppvärmning: 5 min lättjogg, (lätt tänjning 3 min), Spring 30 sekunder, Jogga 30 sekunder. Uppepa i 10 min. <br> Jogga lugnt i 3-5 min efteråt ' ,
				   },
		       'pass2' : {'rubrik' : 'Spring 2/jogga 1-intervaller', 
				  'txt'    : 'Uppvärmning: 3 min lättlogg, tänjningar, spring 2 min, jogga långsamt 1 min. upprepa 5 gånger, (tempo: fortare än bekvämt, ej prattempo, precis innan mjölksyra), nedjogg',
				 },
		       'pass3' : {'rubrik' : '6xbacklöpning med joggvila', 
				  'txt'    : 'Leta upp en 100-150m brant backe, jogga 3-5 min uppvärmning, 2-3 min tränjningar, spring upp, jogga ned, 6 ggr, nedjogg+stretch 3 min',
				 },
		       'pass4' : {'rubrik' : '2x1 km tempolöpning', 
				  'txt'    : 'Uppvärmning: 3 min lättjogg, 3 min tänjningar, 2x1 km tempolöpning, 2 min vila, (mjölksyratröskel, tävlingsfart 5 km), nedjogg 3 min, stretch',
				 },
		       'pass5' : {'rubrik' : 'Fartlek på bana', 
				  'txt'    : 'Uppvärmning: 3 min lättjogg, 2 min tänjningar, 2km fartlek: 400m jogg, 100m löp, 50m sprint, 250m jogg, 300m löp, 200m jogg, 200m löp, 100m jogg, 100m löp, 200m jogg, 100m sprint (jogg: prattempo men ej gå, löp:högre knälyft, EJ prat, sprint: 90-100% av max)',
				 },
		     },
		312: { 'ingress' : 'Svår löpning 30-40 min. <br> INGRESS ',
		       'pass1'   : {'rubrik': '2x10x100m spring 1 ggr/min',
				    'txt'   : 'Uppvärmning 5 min jogg, 2x10x100 m spring 1 ggr/min serievila 5 min, mål: 16-17 s per lopp, nedjogg' ,
				   },
		       'pass2' : {'rubrik' : '10xbacklöpning med joggvila', 
				  'txt'    : '10x backlöpning 120-150m, joggvila 4-5 min (exempelvis runt motionsspåret mellan backar eller tillbaka till samma backe), jogga/löp i sådan takt att du kan hålla samma fart upp för backen i varje lopp/ sprinta upp för backen, nedjogg+stretch',
				 },
		       'pass3' : {'rubrik' : 'Fartlek i terräng', 
				  'txt'    : 'Uppvärmning: 5 min lätt jogg, 5 min tänj/stretch, långfartlek i terräng (variera farten efter känsla då pigg: ruscha ta sikte på ett träd och spring dit sedan jogga/löp efter behag, utför detta i a. 20-30 min',
				 },
		       'pass4' : {'rubrik' : 'Håll-i-gång-träning', 
				  'txt'    : 'Uppvärmning: 5 min hopprep: 50 vanliga hopp, 10 korshopp, 3 dubbelhopp, 10 hopp baklänges, 10 i sedled, 20 så fort som möjligt, BESKRIVNING AVTRÄNINGEN',
				 },
		       'pass5' : {'rubrik' : '3x3x200m med joggvila', 
				  'txt'    : 'uppvärmning 2km inklusive sista 400m i ökat tempo, löpskolning (trippling, skipping, hälkick, ravellisteg, stegringslopp), 3x3x200m med joggvila mellan loppen och serievila efter 3 st 5 min, nedjogg 2-3 min, fotövningar alt. Bara stretch',
				 },
		       
		     },
		313: { 'ingress' : 'Svår löpning 55-60 min. <br> INGRESS  ',
		       
		       'pass1'   : {'Spring 100 backa 50': '',
				    'txt'   : 'uppvärmning: 5-10 min jogg, 10 min löpskolning, 3xstegringslopp 100m <br> Spring 100m, jogga tillbaka 50m, spring 100m etc. tills du är i mål (om du springer på bana, annars spring 7 st. 100m lopp. Upprepa sedan 2 gånger till med 5 min vila mellan omgångarna. <br> Nedjogg 2-3 min + fotövningar, stretch' ,
				   },
                       'pass2' : {'rubrik' : '400m-träning', 
				  'txt'    : 'uppvärmning: 5-10 min jogg, 5 min tänjningar, 10 min löpskolning, 3xstegringslopp 100m, "300+100": spring 300m i tävlingsfart för 400m, gå direkt efter målgång 100m och sprinta sedan 100m. Vila 10 min, 3x150m i maxfart med 250m gåvila, vila 10 min, 300+100, nedjogg, stretch',
				 },
		       'pass3' : {'rubrik' : '400,300,200 i ökad fart', 
				  'txt'    : 'uppvärmning: 5-10 min jogg, 5 min tänjningar,10 min löpskolning, 3xstegringslopp 100m, 5x"Berra-träning", 400, 300, 200 i ökad fart med vila 90 sek. serievila 5 min, exempelvis: 400m: 80s (40s/200m), 300m: 57s (37,5 s/200m), 200m: 35s',
				 },
		       'pass4' : {'rubrik' : '5x600m', 
				  'txt'    : 'Uppvärmning: 5-10 min jogg, 5 min tänjningar, 10 min löpskolning, 3xstegringslopp 100m, 5x600m vila 4 min, tempolöpning, mjölksyra, nedjogg, fotövningar, stretch',
				 },
		       'pass5' : {'rubrik' : 'Kai Abrahamsson träning/800-1500m träning', 
				  'txt'    : 'Uppvärmning 2km löpning varav sista 400m i ökad fart, tänjningar 5 min, löpskolning, 5 min, 3xstegringslopp 100m, 4x300m vila 1,30, 3x200m vila 1,30, vila 7 min, 5x150m, nedjogg, fotövningar, stretch',
				 },
		     },		
		'niva' :[[-1,'Välj nivå'],
			 [1,'Lätt'],
			 [2,'Medel'],
			 [3,'Svår'],
			],
		'form': [[-1,'Välj form'],
			 [1,'Löpning'],
			 [2,'Armar och ben'],
			 [3,'Mage och rygg'],
			],
		'tid':[
		    [-1,'Välj tid'],
		    [1,'15-20 min'],
		    [2,'35-40 min'],
		    [3,'55-60 min'],
		],
		'head':'Träna Nu',
	      };


var data_en = { 111: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'head 1',
				    'txt'   : "English text here"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Engelska',
				 },
		       'pass3' : {'rubrik' : 'HEad 2', 
				  'txt'    : 'ENg',
				 }
		     },

	      };

