var data_sv = { 111: { 'ingress' : 'Enkelt och roligt löppass för alla',
		       'pass1'   : {'rubrik': 'Jogg/gång intervaller',
				    'txt'   : 'Uppvärmning: 5 min gång övergående till lättjogg alternativtlugn gång övergående till gång i raskt takt <br> Tänj 1-3 min (vader, baksida/framsida lår) <br> Spring eller jogga 30 sekunder, gå 2min. Upprepa 3 gånger, gå/jogga lugnt i 3 min som avslutning <br>',
				   }, 
		       'pass2' : {'rubrik' : 'Powerwalk', 
				  'txt'    : 'Spring/jogga intervaller är både ett enkelt och roligt sätt att träna. Med jogga menas i detta pass i princip det långsammaste du kan springa. Med springa menas snababare än jogg, d.v.s. lite mer kraft i steget och jobbigare att utföra. Kom ihåg att det är viktigt att själv hitta en nivå som känns lagom. Det är ingen sprintträning.  <br> Uppvärmning: 5 min powerwalk <br> 3 min tänjningar <br> Spring eller jogga 1 min, gå 2 min. upprepa 3 gånger <br> 2-3 min nedjogg/gå avslappnande',
				 },
                 
                 
		       'pass3' : {'rubrik' : 'Backträning', 
				  'txt'    : 'Leta upp en 100-120m brant backe <br> Uppvärmning: Jogga 3-5 min och tänj sedan vad och lårmuskler i 2-3 min (t.ex. benpendlingar och tänjande utfallssteg) <br> Spring upp/gå i rask takt med långa steg för att sedan gå ned för backen <br> Upprepa 3 gånger. <br>  Stretcha eventuellt baklår och vader efteråt. ',
				 },
                 
                 'pass4' : {'rubrik' : 'Powerwalk', 
				  'txt'    : 'Uppvärmning: 5-8 min gång i promenadtempo övergående till powerwalk alternativt 5-8 min powerwalk övergående till lätt jogg <br> 1 km löpning/jogg/powerwalk (välj själv efter humör men håll samma tempo under hela loppet) <br> Jogga eller gå 2-3 min som en avslappnande avslutning <br> ',
		     },
             
             'pass5' : {'rubrik' : 'Löpskolning', 
				  'txt'    : 'Uppvärmning: 5 min powerwalk/lättjogg <br> Lätt tänjning av <br> framsida/baksida lår (framsida: stå på ett ben, ta tag i ena benet och pressa vadenmot baklåret, knäet ska peka rakt nedåt, upprepa på andra benet) <br> vader (vinkla upp en fot i taget och pressa den mot t.ex. en stolpe, vägg, ett träd eller staket) <br> Löpskolning:  <br> Gå med höga knän på tå först framlänges 30 steg, sedan baklänges 30 steg. Upprepa 3 gånger. <br> Trippla fram med små steg och låga knän i 20m övergående till 20m med höga knän för att sedan övergå till 20m löpning. Tänk på att ha blicken uppåt och att röra armarna rakt framåt hela tiden (helst i 90 graders vinkel)Upprepa 3 gånger. <br> Gå med hälkick (spark i baken) i 20m för att sedan övergå till löpande hälkick i 20m, därefter 20m löpning. Upprepa 3 gånger. <br> Ravellisteg/tennsoldaten (Löp med raka armar och ben på fotbladet) i 20m. Upprepa 3 gånger.<br> 3x100m stegringslopp (gå, jogga, löp, sprinta, löp, jogga, gå) lugn gåvila tillbaka till start. <br> Avsluta med 1-3 min gång/nedjogg för att varva ned. Stretcha vader och lår vid behov. ' ,
                  },
		     },             
	     112: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : 'Uppvärmning: 5 min lättjogg/gå, (lätt tänjning 3 min) spring eller jogga 30 sekunder, gå 2min. Upprepa 3 gånger, gå/jogga 3 minnnn <br> Övning 1, bla bla <br> Övning 2, bla ba'
				   },
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     113: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Uppvärmning: 5 min lättjogg/gå, (lätt tänjning 3 min) spring eller jogga 30 sekunder, gå 2min. Upprepa 3 gånger, gå/jogga 3 minnnn <br> Övning 1, bla bla <br> Övning 2, bla ba"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     211: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Uppvärmning: 5 min lättjogg/gå, (lätt tänjning 3 min) spring eller jogga 30 sekunder, gå 2min. Upprepa 3 gånger, gå/jogga 3 minnnn <br> Övning 1, bla bla <br> Övning 2, bla ba"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     212: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Medel träning lite mer"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     213: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Medel träning mycket mer"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     311: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Svår träning"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     312: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Svår träning lite mer"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
	     313: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'Rub1',
				    'txt'   : "Svår träning mycket mer <br> Övning 1, bla bla <br> Övning 2, bla ba"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Lite Lättare träning <br> Övning 1,bla <br> Övning 2, bla',
				 },
		     },
		'niva' :[[-1,'Välj nivå'],
			[1,'Lätt'],
			[2,'Medel'],
			 [3,'Svår'],
		       ],
		'form': [[-1,'Välj form'],
			 [1,'Löpning'],
			 [2,'Armar'],
			 [3,'Mage'],
			],
		'tid':[
		    [-1,'Välj tid'],
		    [1,'15-20 min'],
		    [2,'35-40 min'],
		    [3,'55-60 min'],
		],
		'head':'Träna Nuu',
	      };


var data_en = { 111: { 'ingress' : 'hej hej',
		       'pass1'   : {'rubrik': 'head 1',
				    'txt'   : "English text here"},
		       'pass2' : {'rubrik' : 'Rub2', 
				  'txt'    : 'Engelska',
				 },
		       'pass3' : {'rubrik' : 'HEad 2', 
				  'txt'    : 'ENg',
				 }
		     },

	      };

